version: "3"
services:
  node:
      container_name: node-production
      restart: always
      image: node
      build: .
      command: npm start
      environment:
        PORT: 5000
        NODE_ENV: production
        MONGODB_URI: mongodb://admin:admin2189@ds121135.mlab.com:21135/heroku_znvgq1mn
        _HOST: d13xat1hwxt21t45.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
        _DATABASE: dhsjy6mzoh4773ml
        _USER: wdd8xfcren9l5awr
        _PASSWORD: x18f261emiwk5rhn
      ports:
        - "5000:5000"
      volumes:
        - .:/usr/app