version: "3"
services:
  node:
      container_name: node-localhost
      restart: always
      image: node
      build: .
      command: npm start
      environment:
        PORT: 5000
        NODE_ENV: localhost
        MONGODB_URI: mongodb://mongodb:27017/study_nodejs
        _HOST: localhost
        _DATABASE: study_nodejs
        _USER: root
        _PASSWORD: 123456
      ports:
        - "5000:5000"
      depends_on:
        - mongodb
        - mysql
      volumes:
        - .:/usr/app
  mongodb:
    container_name: mongo-localhost
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  mysql:
    container_name: mysql-localhost
    image: mysql:5.5
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"